import type { PlanReview } from './types';
import type { DayWorkout, DayMeal } from '@/types/plan';

// Mock workout details - Create 7 days of workouts
const mockWorkoutDetails: DayWorkout[] = [
  {
    day: 1,
    exercises: [
      {
        id: 'ex1-1',
        sessionName: 'Khởi động',
        categoryId: 'cardio',
        exerciseId: 'running',
        minutes: 10,
      },
      {
        id: 'ex1-2',
        sessionName: 'Cardio cường độ cao',
        categoryId: 'cardio',
        exerciseId: 'burpees',
        sets: 3,
        reps: 15,
      },
    ],
  },
  {
    day: 2,
    exercises: [
      {
        id: 'ex2-1',
        sessionName: 'Tập tay',
        categoryId: 'arms',
        exerciseId: 'bicep-curl',
        sets: 4,
        reps: 12,
      },
      {
        id: 'ex2-2',
        sessionName: 'Tập tay sau',
        categoryId: 'arms',
        exerciseId: 'tricep-dips',
        sets: 3,
        reps: 10,
      },
    ],
  },
  {
    day: 3,
    exercises: [
      {
        id: 'ex3-1',
        sessionName: 'Tập ngực',
        categoryId: 'chest',
        exerciseId: 'push-ups',
        sets: 4,
        reps: 15,
      },
      {
        id: 'ex3-2',
        sessionName: 'Tập ngực nâng cao',
        categoryId: 'chest',
        exerciseId: 'bench-press',
        sets: 3,
        reps: 10,
      },
    ],
  },
  {
    day: 4,
    exercises: [
      {
        id: 'ex4-1',
        sessionName: 'Tập lưng',
        categoryId: 'back',
        exerciseId: 'pull-ups',
        sets: 3,
        reps: 8,
      },
      {
        id: 'ex4-2',
        sessionName: 'Tập lưng nâng cao',
        categoryId: 'back',
        exerciseId: 'deadlift',
        sets: 4,
        reps: 6,
      },
    ],
  },
  {
    day: 5,
    exercises: [
      {
        id: 'ex5-1',
        sessionName: 'Tập chân',
        categoryId: 'legs',
        exerciseId: 'squat',
        sets: 4,
        reps: 12,
      },
      {
        id: 'ex5-2',
        sessionName: 'Tập chân nâng cao',
        categoryId: 'legs',
        exerciseId: 'lunges',
        sets: 3,
        reps: 12,
      },
    ],
  },
  {
    day: 6,
    exercises: [
      {
        id: 'ex6-1',
        sessionName: 'Cardio nhẹ',
        categoryId: 'cardio',
        exerciseId: 'cycling',
        minutes: 30,
      },
    ],
  },
  {
    day: 7,
    exercises: [
      {
        id: 'ex7-1',
        sessionName: 'Nghỉ ngơi',
        categoryId: 'core',
        exerciseId: 'plank',
        sets: 3,
        reps: 1,
        minutes: 60,
      },
    ],
  },
];

// Mock meal details - Create 7 days of meals
const mockMealDetails: DayMeal[] = Array.from({ length: 7 }, (_, index) => ({
  menuNumber: index + 1,
  meals: [
    {
      type: 'breakfast',
      ingredients: [
        {
          id: `ing-${index}-1`,
          ingredientId: 'oats',
          weight: 100,
          calories: 389,
          carbs: 66,
          protein: 17,
          fat: 7,
        },
        {
          id: `ing-${index}-2`,
          ingredientId: 'banana',
          weight: 100,
          calories: 89,
          carbs: 23,
          protein: 1.1,
          fat: 0.3,
        },
        {
          id: `ing-${index}-3`,
          ingredientId: 'almonds',
          weight: 30,
          calories: 174,
          carbs: 6.6,
          protein: 6.3,
          fat: 15,
        },
      ],
      totalCalories: 652,
      totalCarbs: 95.6,
      totalProtein: 24.4,
      totalFat: 22.3,
    },
    {
      type: 'lunch',
      ingredients: [
        {
          id: `ing-${index}-4`,
          ingredientId: 'chicken-breast',
          weight: 150,
          calories: 248,
          carbs: 0,
          protein: 46.5,
          fat: 5.4,
        },
        {
          id: `ing-${index}-5`,
          ingredientId: 'brown-rice',
          weight: 200,
          calories: 222,
          carbs: 46,
          protein: 5.2,
          fat: 1.8,
        },
        {
          id: `ing-${index}-6`,
          ingredientId: 'broccoli',
          weight: 100,
          calories: 34,
          carbs: 7,
          protein: 2.8,
          fat: 0.4,
        },
      ],
      totalCalories: 504,
      totalCarbs: 53,
      totalProtein: 54.5,
      totalFat: 7.6,
    },
    {
      type: 'dinner',
      ingredients: [
        {
          id: `ing-${index}-7`,
          ingredientId: 'salmon',
          weight: 150,
          calories: 312,
          carbs: 0,
          protein: 30,
          fat: 19.5,
        },
        {
          id: `ing-${index}-8`,
          ingredientId: 'sweet-potato',
          weight: 200,
          calories: 172,
          carbs: 40,
          protein: 3.2,
          fat: 0.2,
        },
        {
          id: `ing-${index}-9`,
          ingredientId: 'spinach',
          weight: 100,
          calories: 23,
          carbs: 3.6,
          protein: 2.9,
          fat: 0.4,
        },
      ],
      totalCalories: 507,
      totalCarbs: 43.6,
      totalProtein: 36.1,
      totalFat: 20.1,
    },
  ],
}));

export const PENDING_PLANS: PlanReview[] = [
  {
    id: 'plan-review-1',
    userId: 'user1',
    userName: 'Nguyễn Văn A',
    userEmail: 'nguyenvana@example.com',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
    planName: 'Kế hoạch giảm cân 4 tuần',
    planType: 'workout',
    goal: 'Giảm cân, giảm mỡ bụng',
    duration: '4 tuần',
    startDate: '2025-11-20',
    endDate: '2025-12-17',
    status: 'pending',
    totalDays: 28,
    completedDays: 0,
    progress: 0,
    generatedBy: 'ai',
    createdAt: '2025-11-15T10:00:00Z',
    reviewStatus: 'pending',
    submittedAt: '2025-11-15T14:30:00Z',
    workoutDetails: mockWorkoutDetails,
  },
  {
    id: 'plan-review-2',
    userId: 'user2',
    userName: 'Trần Thị B',
    userEmail: 'tranthib@example.com',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
    planName: 'Chế độ ăn healthy 30 ngày',
    planType: 'meal',
    goal: 'Ăn sạch, tăng cường sức khỏe',
    duration: '30 ngày',
    startDate: '2025-11-20',
    endDate: '2025-12-19',
    status: 'pending',
    totalDays: 30,
    completedDays: 0,
    progress: 0,
    generatedBy: 'ai',
    createdAt: '2025-11-16T09:00:00Z',
    reviewStatus: 'pending',
    submittedAt: '2025-11-16T11:20:00Z',
    mealDetails: mockMealDetails,
    healthIssues: ['Khách hàng yêu cầu không ăn thịt đỏ'],
  },
  {
    id: 'plan-review-3',
    userId: 'user3',
    userName: 'Lê Văn C',
    userEmail: 'levanc@example.com',
    userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e',
    planName: 'Kế hoạch tập luyện và dinh dưỡng toàn diện',
    planType: 'combined',
    goal: 'Tăng cơ, giảm mỡ, cải thiện sức khỏe',
    duration: '8 tuần',
    startDate: '2025-11-20',
    endDate: '2026-01-14',
    status: 'pending',
    totalDays: 56,
    completedDays: 0,
    progress: 0,
    generatedBy: 'ai',
    createdAt: '2025-11-17T08:00:00Z',
    reviewStatus: 'pending',
    submittedAt: '2025-11-17T15:45:00Z',
    workoutDetails: mockWorkoutDetails,
    mealDetails: mockMealDetails,
  },
  {
    id: 'plan-review-4',
    userId: 'user4',
    userName: 'Phạm Thị D',
    userEmail: 'phamthid@example.com',
    userAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80',
    planName: 'Tăng cơ bắp hiệu quả',
    planType: 'workout',
    goal: 'Tăng cơ, tăng sức mạnh',
    duration: '6 tuần',
    startDate: '2025-11-18',
    endDate: '2025-12-29',
    status: 'pending',
    totalDays: 42,
    completedDays: 0,
    progress: 0,
    generatedBy: 'ai',
    createdAt: '2025-11-18T10:30:00Z',
    reviewStatus: 'pending',
    submittedAt: '2025-11-18T16:20:00Z',
    workoutDetails: mockWorkoutDetails,
  },
];

