import type { CustomerDetail, MonthlyCustomer } from './types';

export const MONTHLY_CUSTOMERS: MonthlyCustomer[] = [
  {
    id: 'cus-001',
    name: 'Trần Hoàng Minh',
    email: 'minh.th@fitai.com',
    phone: '0901 234 567',
    month: '2025-11',
    goal: 'Giảm 3kg và cải thiện sức bền',
    plan: 'Gói Premium 3 tháng',
    status: 'on-track',
    engagement: 'high',
    sessionsCompleted: 7,
    sessionsTarget: 12,
    progressPercent: 64,
    lastCheckIn: '10/11/2025',
    nextSession: '14/11/2025',
    weightChange: '-1.2kg',
    notes: 'Rất chủ động ghi chép bài tập và phản hồi sau mỗi buổi.',
  },
  {
    id: 'cus-002',
    name: 'Nguyễn Thị Hạnh',
    email: 'hanh.nt@fitai.com',
    phone: '0907 888 123',
    month: '2025-11',
    goal: 'Cân bằng dinh dưỡng và giảm mỡ bụng',
    plan: 'Gói Dinh dưỡng 1-1',
    status: 'at-risk',
    engagement: 'medium',
    sessionsCompleted: 5,
    sessionsTarget: 10,
    progressPercent: 48,
    lastCheckIn: '08/11/2025',
    nextSession: '13/11/2025',
    weightChange: '-0.4kg',
    notes: 'Cần nhắc lịch ăn và ngủ đều đặn hơn trong tuần này.',
  },
  {
    id: 'cus-003',
    name: 'Phạm Quốc Toàn',
    email: 'toan.pq@fitai.com',
    phone: '0912 456 789',
    month: '2025-11',
    goal: 'Tăng cơ tay và ngực',
    plan: 'Training Plan 12 buổi',
    status: 'on-track',
    engagement: 'high',
    sessionsCompleted: 8,
    sessionsTarget: 12,
    progressPercent: 72,
    lastCheckIn: '11/11/2025',
    nextSession: '15/11/2025',
    weightChange: '+0.8kg',
  },
  {
    id: 'cus-004',
    name: 'Lê Thanh Ngọc',
    email: 'ngoc.lt@fitai.com',
    month: '2025-11',
    goal: 'Cải thiện chất lượng giấc ngủ',
    plan: 'Wellness Coaching',
    status: 'behind',
    engagement: 'low',
    sessionsCompleted: 3,
    sessionsTarget: 8,
    progressPercent: 30,
    lastCheckIn: '03/11/2025',
    nextSession: '17/11/2025',
    notes: 'Khó duy trì lịch trình do công việc tăng cao.',
  },
  {
    id: 'cus-005',
    name: 'Đỗ Tấn Phát',
    email: 'phat.dt@fitai.com',
    phone: '0933 222 456',
    month: '2025-11',
    goal: 'Giảm 5% mỡ cơ thể',
    plan: 'Hybrid Nutrition & Training',
    status: 'on-track',
    engagement: 'medium',
    sessionsCompleted: 6,
    sessionsTarget: 12,
    progressPercent: 58,
    lastCheckIn: '09/11/2025',
    nextSession: '16/11/2025',
    weightChange: '-1.0kg',
  },
  {
    id: 'cus-006',
    name: 'Vũ Hoài Nam',
    email: 'nam.vh@fitai.com',
    phone: '0915 678 910',
    month: '2025-11',
    goal: 'Tăng sức bền tim mạch',
    plan: 'Endurance Advance',
    status: 'at-risk',
    engagement: 'medium',
    sessionsCompleted: 4,
    sessionsTarget: 10,
    progressPercent: 42,
    lastCheckIn: '06/11/2025',
    nextSession: '14/11/2025',
    notes: 'Cần điều chỉnh cường độ bài tập để phù hợp thể trạng.',
  },
  {
    id: 'cus-007',
    name: 'Huỳnh Mỹ Duyên',
    email: 'duyen.hm@fitai.com',
    month: '2025-11',
    goal: 'Tăng năng lượng và cân bằng hormone',
    plan: 'Wellness+ 1 năm',
    status: 'on-track',
    engagement: 'high',
    sessionsCompleted: 9,
    sessionsTarget: 12,
    progressPercent: 78,
    lastCheckIn: '12/11/2025',
    nextSession: '18/11/2025',
  },
  {
    id: 'cus-008',
    name: 'Bùi Văn Hải',
    email: 'hai.bv@fitai.com',
    month: '2025-11',
    goal: 'Chuẩn bị giải chạy 10km',
    plan: 'Race Builder 8 tuần',
    status: 'behind',
    engagement: 'medium',
    sessionsCompleted: 2,
    sessionsTarget: 8,
    progressPercent: 25,
    lastCheckIn: '02/11/2025',
    nextSession: '13/11/2025',
    notes: 'Đề xuất chuyển sang lịch tập buổi sáng.',
  },
  {
    id: 'cus-009',
    name: 'Ngô Thảo Vy',
    email: 'vy.nt@fitai.com',
    phone: '0977 123 999',
    month: '2025-11',
    goal: 'Cải thiện dáng và săn cơ',
    plan: 'Coaching PT 24 buổi',
    status: 'on-track',
    engagement: 'high',
    sessionsCompleted: 10,
    sessionsTarget: 16,
    progressPercent: 68,
    lastCheckIn: '09/11/2025',
    nextSession: '13/11/2025',
  },
  {
    id: 'cus-010',
    name: 'Lý Đức Anh',
    email: 'anh.ld@fitai.com',
    month: '2025-10',
    goal: 'Tăng cân lành mạnh',
    plan: 'Nutrition Coaching 3 tháng',
    status: 'on-track',
    engagement: 'medium',
    sessionsCompleted: 10,
    sessionsTarget: 12,
    progressPercent: 82,
    lastCheckIn: '26/10/2025',
    nextSession: '31/10/2025',
    weightChange: '+2.2kg',
  },
  {
    id: 'cus-011',
    name: 'Phan Thanh Bình',
    email: 'binh.pt@fitai.com',
    month: '2025-10',
    goal: 'Giảm đau lưng và cải thiện tư thế',
    plan: 'Physio Mobility',
    status: 'at-risk',
    engagement: 'low',
    sessionsCompleted: 4,
    sessionsTarget: 10,
    progressPercent: 40,
    lastCheckIn: '18/10/2025',
    nextSession: '25/10/2025',
    notes: 'Chưa sắp xếp được lịch cố định, cần trao đổi thêm.',
  },
  {
    id: 'cus-012',
    name: 'Đinh Thị Mai',
    email: 'mai.dt@fitai.com',
    month: '2025-10',
    goal: 'Duy trì vóc dáng và kiểm soát stress',
    plan: 'Wellness Coaching',
    status: 'on-track',
    engagement: 'high',
    sessionsCompleted: 11,
    sessionsTarget: 12,
    progressPercent: 90,
    lastCheckIn: '28/10/2025',
    nextSession: '01/11/2025',
  },
];

const MONTHLY_CUSTOMER_MAP = MONTHLY_CUSTOMERS.reduce<Record<string, MonthlyCustomer>>((acc, customer) => {
  acc[customer.id] = customer;
  return acc;
}, {});

export const CUSTOMER_DETAILS: Record<string, CustomerDetail> = {
  'cus-001': {
    ...MONTHLY_CUSTOMER_MAP['cus-001'],
    age: 28,
    gender: 'male',
    joinedDate: '01/10/2024',
    packageName: 'Premium - 3 tháng',
    height: 175,
    currentWeight: 75,
    medicalHistory: 'Không có tiền sử bệnh lý',
    remarks: 'Khách hàng rất chăm chỉ và có động lực cao',
    measurements: [
      { date: '01/10', weight: 75, bodyFat: 22, boneMass: 35 },
      { date: '08/10', weight: 74, bodyFat: 21, boneMass: 35.5 },
      { date: '15/10', weight: 73, bodyFat: 20, boneMass: 36 },
      { date: '22/10', weight: 72, bodyFat: 19.5, boneMass: 36.5 },
    ],
  },
  'cus-002': {
    ...MONTHLY_CUSTOMER_MAP['cus-002'],
    age: 32,
    gender: 'female',
    joinedDate: '15/09/2024',
    packageName: 'Nutrition Focus 6 tháng',
    height: 162,
    currentWeight: 61,
    medicalHistory: 'Đã từng thiếu máu nhẹ, theo dõi dinh dưỡng 2023',
    remarks: 'Cần hỗ trợ tạo thói quen ăn sáng và ngủ trước 23h',
    measurements: [
      { date: '05/10', weight: 62, bodyFat: 28, boneMass: 30.5 },
      { date: '12/10', weight: 61.8, bodyFat: 27.6, boneMass: 30.6 },
      { date: '19/10', weight: 61.5, bodyFat: 27.2, boneMass: 30.7 },
      { date: '26/10', weight: 61.2, bodyFat: 27, boneMass: 30.7 },
    ],
  },
};

export const findCustomerDetailById = (id: string): CustomerDetail | null => {
  if (CUSTOMER_DETAILS[id]) {
    return CUSTOMER_DETAILS[id];
  }

  const base = MONTHLY_CUSTOMER_MAP[id];
  if (!base) {
    return null;
  }

  return {
    ...base,
  };
};

