import type { FeedbackSubmission } from './types';

export const FEEDBACK_SUBMISSIONS: FeedbackSubmission[] = [
  {
    id: 'fb-001',
    customerName: 'Đinh Thị Mai',
    customerEmail: 'mai.dt@fitai.com',
    submittedAt: '2025-11-09T08:35:00+07:00',
    workoutName: 'Squat cơ bản',
    focusArea: 'Form và độ sâu',
    notesFromCustomer: 'Em thấy đầu gối hơi run, nhờ coach kiểm tra giúp.',
    mediaType: 'video',
    mediaUrl: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=60',
    status: 'pending',
    category: 'training',
  },
  {
    id: 'fb-002',
    customerName: 'Nguyễn Hoàng Nam',
    customerEmail: 'nam.nh@fitai.com',
    submittedAt: '2025-11-10T10:10:00+07:00',
    workoutName: 'Plank nâng cao',
    focusArea: 'Độ thẳng của lưng',
    notesFromCustomer: 'Không chắc phần lưng có giữ thẳng không.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=900&q=60',
    status: 'rework',
    advisorNotes: 'Nhắc khách hàng siết core mạnh hơn, thử đặt gương ngang.',
    category: 'training',
  },
  {
    id: 'fb-003',
    customerName: 'Lê Mỹ Linh',
    customerEmail: 'linh.lm@fitai.com',
    submittedAt: '2025-11-08T21:20:00+07:00',
    workoutName: 'Deadlift Romanian',
    focusArea: 'Hông và lưng dưới',
    mediaType: 'video',
    mediaUrl: 'https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1526402462755-71f7e71b0f21?auto=format&fit=crop&w=800&q=60',
    status: 'pending',
    category: 'training',
  },
  {
    id: 'fb-004',
    customerName: 'Trần Tấn Phát',
    customerEmail: 'phat.tt@fitai.com',
    submittedAt: '2025-11-07T18:05:00+07:00',
    workoutName: 'Hít đất kim cương',
    focusArea: 'Vị trí khuỷu tay',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1546484959-f9a2119b9e55?auto=format&fit=crop&w=900&q=60',
    status: 'reviewed',
    advisorNotes: 'Form ổn, tiếp tục giữ nhịp thở đều.',
    category: 'training',
  },
  {
    id: 'fb-005',
    customerName: 'Phạm Bảo Châu',
    customerEmail: 'chau.pb@fitai.com',
    submittedAt: '2025-11-09T07:15:00+07:00',
    workoutName: 'Thực đơn sáng 450kcal',
    focusArea: 'Tỷ lệ carb 40%',
    notesFromCustomer: 'Em thêm 1 ly sữa hạnh nhân, coach xem còn phù hợp không?',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=900&q=60',
    status: 'pending',
    category: 'nutrition',
  },
  {
    id: 'fb-006',
    customerName: 'Võ Anh Minh',
    customerEmail: 'minh.va@fitai.com',
    submittedAt: '2025-11-06T20:45:00+07:00',
    workoutName: 'Nhật ký ăn uống ngày 10/11',
    focusArea: 'Đủ đạm buổi tối',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=900&q=60',
    status: 'reviewed',
    advisorNotes: 'Khuyến khích thêm 1 khẩu phần rau xanh, hạn chế nước ngọt.',
    category: 'nutrition',
  },
];
